### ISSUE TITLE
Part cooling logic seems to be broken

### ISSUE THREAD

**Issue by H4kunaM4tata** [SoftFever/BambuStudio-SoftFever#154]
**Describe the bug**
I have this option disabled because I don't wanna part cooling on at all for the first 2 layers.
At least that is what I expect it to do.

![image](https://user-images.githubusercontent.com/35049512/211465243-3692be48-1af0-494c-b34d-c3b2116942f6.png)

But that fully disables the part cooling for all the bottom and top layers which is wrong.

**To Reproduce**
1. Disable keep fan always on
2. Slice
3. Check the fan speed color scheme

![image](https://user-images.githubusercontent.com/35049512/211464828-247ccfce-6d98-4bcc-ad32-e47096462806.png)

If I do enable keep fan always on, then it does work as expected.
Or I am missing something or something doesn't seem right.

![image](https://user-images.githubusercontent.com/35049512/211464995-55408fae-dde0-4f28-95fb-c16cdcc2137c.png)

Thank you

**Comment by SoftFever** [comment]
I haven't dug into this part yet. 
My hunch is that when you have `keep fan always on` off, the slicer will turn off the fan speed if the auto-calculated fan speed is below the min fan speed. In your case, the min fan speed is 100%.
So when the calculated fan speed(based on layer time) is below 100%, the fan will be turned off.
Sounds like an expected behavior to me.

**Comment by H4kunaM4tata** [comment]
@SoftFever I confess I am lost here with that logic.
I will use what works as expected for me, since this is an expected behavior, I am closing this.
Thank you
