### ISSUE TITLE
auto sync user presets for 3rd party printer profiles

### ISSUE THREAD

**Issue by bavery79** [SoftFever/BambuStudio-SoftFever#74]
Got a bit excited about Bambu's ability to sync printer/filament/process data from Bambu cloud, but this either doesn't appear to work properly, or maybe some issue with the way 3rd party printer profiles are handled with this SoftFever fork?  Either way, would love to see the profile sync work for non-Bambu printers.

**Comment by SoftFever** [comment]
The syncing feature worked well until Bambu made changes in their cloud since 1.4.
It looks like their cloud checks the setting id and refuses the request if the id is not a BBL printer.
While I think I can hack to make it work now, it's indeed better to have the capability to sync with Google/Apple drive in the long run.

**Comment by SoftFever** [comment]
fixed
